### ISSUE TITLE
What needs work?

### ISSUE THREAD

**Issue by conradev** [flier/rust-macho#2]
Hi @flier, this library looks awesome and replete with features. I would love to help develop it out further. What parts still need work? What features do you want to add?

Would love to get continuous integration and hosted documentation set up so that the library is easier to develop and use.

**Comment by flier** [comment]
Sure, we have a travis [CI build](https://travis-ci.org/flier/rust-macho) and a simple [API reference](http://flier.github.io/rust-macho/doc/macho/index.html), I think you could contribute your comments or examples to those documents, or design a user guide with readability. :)

For the features, welcome to submit your wish list, because I major focus on my internal project.

**Comment by flier** [comment]
Sure, we have a travis CI build <https://travis-ci.org/flier/rust-macho>
and a simple API reference
<http://flier.github.io/rust-macho/doc/macho/index.html>, I think you could
contribute your comments or examples to those documents, or design a user
guide with readability. :)

For the features, welcome to submit your wish list, because I major focus
on my internal project.

Conrad Kramer <notifications@github.com>于2016年10月26日周三 上午9:07写道：

**Comment by conradev** [comment]
Awesome! I can work on putting the CI status and documentation link in the `README` so that they are visible, and can perhaps work on a user guide.

I'm not sure if this is in scope, but I would love to have symbol parsing based on a given `SymTab` load command (essentially everything in `nlist.h`). I'm working right now on a project that does this, and can contribute it upstream when I am done!

EDIT: I see you did that already – awesome!

**Comment by flier** [comment]
no problem, you could try to parse the symtab command, or submit a feature request and I will follow up it soon :)

**Comment by flier** [comment]
I made a fast prototype for symtab, please let's me know your comments :)

https://github.com/flier/rust-macho/tree/symtab

**Comment by conradev** [comment]
This is awesome. This looks extremely similar to what I implemented, but way more complete! I, too, implemented an iterator.

The only difference between mine and yours is that I didn't copy the name to `String`, and instead parsed it as a `&str`. I'm not sure if this is possible with the current way the library is implemented, but not having to copy the strings would be more performant ✌️:

`let name = str::from_utf8(*&slice[stroff + strx..].split(|x| *x == 0).next().unwrap()).unwrap();`

**Comment by flier** [comment]
sure, [load &str instead of String](https://github.com/flier/rust-macho/commit/9bd97564d40aed9590a94fbdf2f7232358152785) will be better, although need a few  lifetime annotation. 

I made a pull request #3 for this, please check it, thanks
